# Generated by Django 5.2 on 2025-08-31 14:30

import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[contact.validators.phone_validators]),
        ),
    ]
