# Generated by Django 5.2 on 2025-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desription1', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='about/')),
                ('services_title', models.CharField(max_length=50)),
                ('services_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Peculiarities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.TextField(max_length=100)),
                ('description2', models.TextField(max_length=200)),
                ('is_visible', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('service_sign', models.CharField(choices=[('fa fa-truck fa-lg', 'Car'), ('fa fa-percent', 'Percent'), ('fa fa-user', 'User'), ('fa fa-comment', 'Comments'), ('fa fa-phone', 'Phone'), ('fa fa-shopping-cart', 'ShoppingCart'), ('fa fa-home', 'Home'), ('fa fa-search', 'Search')], max_length=50)),
            ],
        ),
    ]
