# Generated by Django 5.2 on 2025-08-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Us',
            new_name='AboutUs',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='peculiarities',
            options={'ordering': ['-created'], 'verbose_name': 'Peculiarities', 'verbose_name_plural': 'Peculiarities'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='desription1',
            new_name='description1',
        ),
    ]
